### ISSUE TITLE
Files not exists

### ISSUE THREAD

**Issue by hyperji** [mwsill/mnp_training#1]
## I try to run the preprocessing.R but throwed a error as below, are thosed files' name changed?

Error in read.metharray(filepath, verbose = TRUE): The following specified files do not exist:GSE90496_RAW/GSM2402866_5684819013_R02C01_Grn.idat, GSE90496_RAW/GSM2402915_6929689168_R06C01_Grn.idat, GSE90496_RAW/GSM2402916_6929689168_R01C02_Grn.idat, GSE90496_RAW/GSM2402917_6164621144_R04C02_Grn.idat, GSE90496_RAW/GSM2402918_6969568004_R01C01_Grn.idat, GSE90496_RAW/GSM2402919_6164621144_R04C01_Grn.idat, GSE90496_RAW/GSM2402920_6164621144_R05C01_Grn.idat, GSE90496_RAW/GSM2402921_6164621144_R02C01_Grn.idat, GSE90496_RAW/GSM2402953_6164621144_R03C02_Grn.idat, GSE90496_RAW/GSM2402954_6164621144_R02C02_Grn.idat, GSE90496_RAW/GSM2402955_6164621144_R06C01_Grn.idat, GSE90496_RAW/GSM2402956_6164621144_R01C02_Grn.idat, GSE90496_RAW/GSM2402957_6969568004_R02C01_Grn.idat, GSE90496_RAW/GSM2402958_6929718017_R01C01_Grn.idat, GSE90496_RAW/GSM2402959_6929718027_R01C01_Grn.idat, GSE90496_RAW/GSM2402960_6929718027_R02C01_Grn.idat, GSE90496_RAW/GSM2402961_6929718026_R05C02_Grn.idat, GSE90496_RAW/GSM2402962_6929718027_R06C01_Grn.idat, GSE90496_RAW/GSM2402963_6929718027_R04C01_Grn.idat, GSE90496_RAW/GSM2402974_6929718026_R06C01_Grn.idat, GSE90496_RAW/GSM2402975_6929718026_R01C02_Grn.idat, GSE90496_RAW/GSM2402977_6929718027_R04C02_Grn.idat, GSE90496_RAW/GSM2403026_6929718049_R06C01_Grn.idat, GSE90496_RAW/GSM2403027_6929718049_R03C01_Grn.idat, GSE90496_RAW/GSM2403063_6229017023_R05C01_Grn.idat, GSE90496_RAW/GSM2403068_6229017022_R02C02_Grn.idat, GSE90496_RAW/GSM2403070_6229017022_R06C02_Grn.idat, GSE90496_RAW/GSM2403072_6247004023_R03C02_Grn.idat, GSE90496_RAW/GSM2403073_6247004023_R04C02_Grn.idat, GSE90496_RAW/GSM2403076_6247004024_R03C01_Grn.idat, GSE90496_RAW/GSM2403463_8622007027_R01C01_Grn.idat, GSE90496_RAW/GSM2403496_8622007061_R03C01_Grn.idat, GSE90496_RAW/GSM2403619_8622007130_R04C01_Grn.idat, GSE90496_RAW/GSM2403719_9007225017_R01C02_Grn.idat, GSE90496_RAW/GSM2403893_9297949147_R02C02_Grn.idat, GSE90496_RAW/GSM2404046_9373550131_R02C02_Grn.idat, GSE90496_RAW/GSM2404097_9376538156_R01C02_Grn.idat, GSE90496_RAW/GSM2404098_9376538156_R02C01_Grn.idat, GSE90496_RAW/GSM2404099_9376538156_R03C01_Grn.idat, GSE90496_RAW/GSM2404100_9376538156_R03C02_Grn.idat, GSE90496_RAW/GSM2404119_9376561062_R05C01_Grn.idat, GSE90496_RAW/GSM2404123_9379086124_R05C01_Grn.idat, GSE90496_RAW/GSM2404124_9379086124_R04C01_Grn.idat, GSE90496_RAW/GSM2404125_9379086129_R06C01_Grn.idat, GSE90496_RAW/GSM2404126_9379086129_R01C02_Grn.idat, GSE90496_RAW/GSM2404127_9379086124_R01C02_Grn.idat, GSE90496_RAW/GSM2404128_9379086124_R02C02_Grn.idat, GSE90496_RAW/GSM2404148_9407201022_R06C01_Grn.idat, GSE90496_RAW/GSM2404149_9407201022_R03C02_Grn.idat, GSE90496_RAW/GSM2404150_9407201022_R06C02_Grn.idat, GSE90496_RAW/GSM2404151_9407201021_R02C02_Grn.idat, GSE90496_RAW/GSM2404152_9407201022_R03C01_Grn.idat, GSE90496_RAW/GSM2404153_9407201022_R04C01_Grn.idat, GSE90496_RAW/GSM2404154_9407201022_R01C02_Grn.idat, GSE90496_RAW/GSM2404155_9407201022_R04C02_Grn.idat, GSE90496_RAW/GSM2404156_9407201021_R02C01_Grn.idat, GSE90496_RAW/GSM2404157_9407201021_R06C01_Grn.idat, GSE90496_RAW/GSM2404158_9407201021_R04C02_Grn.idat, GSE90496_RAW/GSM2404159_9407201022_R01C01_Grn.idat, GSE90496_RAW/GSM2404160_9407201022_R05C01_Grn.idat, GSE90496_RAW/GSM2404161_9407201022_R02C02_Grn.idat, GSE90496_RAW/GSM2404162_9407201022_R05C02_Grn.idat, GSE90496_RAW/GSM2404163_9407201025_R01C01_Grn.idat, GSE90496_RAW/GSM2404164_9407201021_R03C01_Grn.idat, GSE90496_RAW/GSM2404165_9407201021_R01C02_Grn.idat, GSE90496_RAW/GSM2404166_9407201021_R05C02_Grn.idat, GSE90496_RAW/GSM2404167_9407201021_R05C01_Grn.idat, GSE90496_RAW/GSM2404168_9407201022_R02C01_Grn.idat, GSE90496_RAW/GSM2404379_9422493151_R06C02_Grn.idat, GSE90496_RAW/GSM2404483_9444374134_R02C02_Grn.idat, GSE90496_RAW/GSM2404519_9444374147_R03C01_Grn.idat, GSE90496_RAW/GSM2404775_9769100007_R02C02_Grn.idat, GSE90496_RAW/GSM2404776_9769100008_R02C01_Grn.idat, GSE90496_RAW/GSM2404833_9533774082_R01C01_Grn.idat, GSE90496_RAW/GSM2404834_9533774082_R03C01_Grn.idat, GSE90496_RAW/GSM2404835_9533774082_R04C01_Grn.idat, GSE90496_RAW/GSM2404836_9533774082_R05C01_Grn.idat, GSE90496_RAW/GSM2404837_9533774082_R06C01_Grn.idat, GSE90496_RAW/GSM2404838_9533774082_R01C02_Grn.idat, GSE90496_RAW/GSM2404839_9533774082_R04C02_Grn.idat, GSE90496_RAW/GSM2404840_9533774082_R06C02_Grn.idat, GSE90496_RAW/GSM2404841_9533774084_R02C01_Grn.idat, GSE90496_RAW/GSM2404842_9533774084_R03C01_Grn.idat, GSE90496_RAW/GSM2404843_9533774084_R04C01_Grn.idat, GSE90496_RAW/GSM2404844_9533774084_R06C01_Grn.idat, GSE90496_RAW/GSM2404854_9534104010_R06C02_Grn.idat, GSE90496_RAW/GSM2404880_9534104026_R01C01_Grn.idat, GSE90496_RAW/GSM2404881_9534104026_R02C01_Grn.idat, GSE90496_RAW/GSM2404882_9534104026_R05C01_Grn.idat, GSE90496_RAW/GSM2404926_9969477003_R01C01_Grn.idat, GSE90496_RAW/GSM2404927_9969477003_R02C01_Grn.idat, GSE90496_RAW/GSM2405010_9969477043_R06C02_Grn.idat, GSE90496_RAW/GSM2405011_9969477044_R01C01_Grn.idat, GSE90496_RAW/GSM2405012_9969477044_R02C02_Grn.idat, GSE90496_RAW/GSM2405013_9969477044_R03C02_Grn.idat, GSE90496_RAW/GSM2405014_9969477044_R06C01_Grn.idat, GSE90496_RAW/GSM2405015_9969477044_R02C01_Grn.idat, GSE90496_RAW/GSM2405016_9969477044_R04C02_Grn.idat, GSE90496_RAW/GSM2405017_9969477044_R01C02_Grn.idat, GSE90496_RAW/GSM2405043_9969477079_R06C02_Grn.idat, GSE90496_RAW/GSM2405081_9969477098_R04C01_Grn.idat, GSE90496_RAW/GSM2405210_9878820127_R04C01_Grn.idat, GSE90496_RAW/GSM2405211_9878820127_R05C01_Grn.idat, GSE90496_RAW/GSM2405251_9878827227_R04C01_Grn.idat, GSE90496_RAW/GSM2405372_3999834063_R02C02_Grn.idat, GSE90496_RAW/GSM2405438_3999875073_R01C01_Grn.idat, GSE90496_RAW/GSM2405448_3999875052_R05C01_Grn.idat, GSE90496_RAW/GSM2405449_3999875052_R01C02_Grn.idat, GSE90496_RAW/GSM2405450_3999875052_R02C02_Grn.idat, GSE90496_RAW/GSM2405520_3998909027_R02C02_Grn.idat, GSE90496_RAW/GSM2405521_3998909027_R03C02_Grn.idat, GSE90496_RAW/GSM2405522_3998909027_R04C02_Grn.idat
Traceback:

1. read.metharray(filepath, verbose = TRUE)
2. stop("The following specified files do not exist:", paste(noexits, 
 .     collapse = ", "))

**Comment by mwsill** [comment]
you need to download the RAW data from GEO first
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE90496

**Comment by hyperji** [comment]
Thank you.
