### ISSUE TITLE
Access to existing classifiers

### ISSUE THREAD

**Issue by rowanhowellGE** [mwsill/mnp_training#5]
Hi,

Is there any way to download the RF classifier and calibration model used for https://www.molecularneuropathology.org/mnp/ and/or the original Capper et al. 2018 publication, rather than training your own?

Thanks

**Comment by mwsill** [comment]
Hi,

We do have a R-package that includes the complete pipeline available on the website. However, we are only allowed to share this with other public research institutes and universities that have signed a cooperation agreement with us. So if you are from a university or public institute, feel free to contact me via my kitz or dkfz mail. 

Best,

Martin
